inventarios/bodegas/urls.py
from django.urls import path
from django.views.generic import RedirectView
from bodegas import views as modelViews

bodegas_patterns = ([
    path('',                modelViews.baseListView.as_view(),  name="Base"),
    path('add',             modelViews.CreateView.as_view(),    name="Add"),
    path('edit/<int:pk>',   modelViews.UpdateView.as_view(),    name="Edit"),
    path('del/<int:pk>',    modelViews.DeleteView.as_view(),    name="Delete"),
    path('search',          modelViews.Search,                  name='Search'),
    path('export',          modelViews.exportExcel,             name="exportExcel"),
], "Bodegas")

inventarios/inventarios/urls.py
from django.urls import path
from django.views.generic import RedirectView
from inventarios import views as modelViews

inventarios_patterns = ([
    path('',                modelViews.baseListView.as_view(),name="Base"),
    path('add',             modelViews.CreateView.as_view(),  name="Add"),
    path('edit/<int:pk>',   modelViews.UpdateView.as_view(),  name="Edit"),
    path('del/<int:pk>',    modelViews.DeleteView.as_view(),  name="Delete"),
    path('search',          modelViews.Search,                name='Search'),
    path('getProduct',      modelViews.GetProduct,            name='GetProductAjax'),
    path('addProduct',      modelViews.AddProduct,            name='AddProductAjax'),
    path('export',          modelViews.exportExcel,           name="exportExcel"),
], "Inventarios")

inventarios/inventariosBase/urls.py
from django.contrib import admin
from django.urls import path, include

from codeBackEnd.urls import codeBackEnd_patterns
from inventarios.urls import inventarios_patterns
from categorias.urls import categorias_patterns
from bodegas.urls import bodegas_patterns
from proveedores.urls import proveedores_patterns
from transaccionesInventarios.urls import transaccionesInv_patterns
from usuarios.urls import usuarios_patterns

urlpatterns = [
    path('DJAdmin/', admin.site.urls),

    # Paths del auth
    path('', include('django.contrib.auth.urls')),

    # Paths de Admin
    path('', include(codeBackEnd_patterns)),
    path('usuarios/',        include(usuarios_patterns)),

    path('inventarios/',        include(inventarios_patterns)),
    path('categorias/',         include(categorias_patterns)),
    path('bodegas/',            include(bodegas_patterns)),
    path('proveedores/',        include(proveedores_patterns)),
    path('transaccionesInv/',   include(transaccionesInv_patterns)),
]

inventarios/inventarios/models.py
from django.db import models
from categorias.models import Categorias

# Create your models here.
class Productos(models.Model):
    nombre          = models.CharField(max_length=100, verbose_name="Nombre")
    cantidad        = models.IntegerField(verbose_name="Cantidad", default=0)
    codigoProduto   = models.CharField(max_length=50, verbose_name="Código del producto", default="0")
    descripcion     = models.CharField(max_length=155, verbose_name="Descripción", default="No indicado")
    categoria       = models.ManyToManyField(Categorias, verbose_name="Categoria", blank=True)

    def __str__(self):
        return self.nombre

inventarios/inventarios/forms.py
from django import forms
from .models import Productos

class BaseForm(forms.ModelForm):
    class Meta:
        model = Productos
        fields = [
            'nombre',
            'cantidad',
            'codigoProduto',
            'categoria',
            'descripcion',
        ]

        widgets = {
            'nombre'        : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'cantidad'      : forms.TextInput(attrs={'class': 'form-control' , 'placeholder': 'Cantidad'}),
            'codigoProduto' : forms.TextInput(attrs={'class': 'form-control' , 'placeholder': 'Código del producto / EAN'}),
            'descripcion'   : forms.Textarea(attrs={'class': 'form-control' , 'placeholder': 'Descripción', 'required': 'true'}),
        }

class FormEdit(forms.ModelForm):
    class Meta:
        model = Productos
        fields = [
            'nombre',
            'codigoProduto',
            'categoria',
            'descripcion',
        ]

        widgets = {
            'nombre'        : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'codigoProduto' : forms.TextInput(attrs={'class': 'form-control' , 'placeholder': 'Código del producto'}),
            'descripcion'   : forms.Textarea(attrs={'class': 'form-control' , 'placeholder': 'Descripción', 'required': 'true'}),
        }

inventarios/inventarios/views.py
import json
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse_lazy, reverse
from django.http import JsonResponse
from .models import Productos
from .forms import BaseForm, FormEdit
from usuarios.views import consultar_PermisoUsuario
from codeBackEnd.funciones import estructuraExcel
from categorias.models import Categorias

# Create your views here.
class baseListView(ListView):
    model = Productos
    template_name = 'inventarios/List.html'
    paginate_by = 30

    ordering = ['-nombre']

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated == False:
            return redirect('login')
        else:
            if consultar_PermisoUsuario(request, 'inventarios.view_productos'):
                return super().dispatch(request, *args, *kwargs)
            else:
                return redirect('codeBackEnd:dashboard')

class DeleteView(DeleteView):
    model = Productos
    template_name = 'inventarios/Del.html'
    success_url = reverse_lazy('Inventarios:Base')

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated == False:
            return redirect('login')
        else:
            if consultar_PermisoUsuario(request, 'inventarios.delete_productos'):
                return super().dispatch(request, *args, *kwargs)
            else:
                return redirect('Inventarios:Base')

class CreateView(CreateView):
    model = Productos
    form_class = BaseForm
    template_name = 'inventarios/Add.html'
    
    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated == False:
            return redirect('login')
        else:
            if consultar_PermisoUsuario(request, 'inventarios.add_productos'):
                return super().dispatch(request, *args, *kwargs)
            else:
                return redirect('Inventarios:Base')

    def get_success_url(self):
        # return reverse_lazy('comercioAdmin:producto', kwargs={ 'pk': self.object.id })
        return reverse_lazy('Inventarios:Base') + '?created'

class UpdateView(UpdateView):
    model = Productos
    form_class = FormEdit
    template_name = 'inventarios/Edit.html'
    # exclude = ('cantidad',)
    
    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated == False:
            return redirect('login')
        else:
            if consultar_PermisoUsuario(request, 'inventarios.change_productos'):
                return super().dispatch(request, *args, *kwargs)
            else:
                return redirect('Inventarios:Base')

    def get_success_url(self):
        return reverse_lazy('Inventarios:Edit', args=[self.object.id]) + '?updated'

def Search(request):
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'inventarios.view_productos'):
            filtroNombre = request.GET.get('nombre', '')
            filtroCodigo = request.GET.get('codigoProduto', '')
            filtroCategoria = request.GET.get('categoria', '')

            # trae los productos relacionados
            filtro_list = []

            if filtroNombre != '' and filtroNombre != None:
                filtro_list = Productos.objects.filter(nombre__icontains=filtroNombre)
            elif filtroCodigo != '' and filtroCodigo != None:
                filtro_list = Productos.objects.filter(codigoProduto__icontains=filtroCodigo)
            elif filtroCategoria != '' and filtroCategoria != None:
                filtro_list = Productos.objects.filter(categoria__id=filtroCategoria)
            else:
                return redirect(reverse_lazy('Inventarios:Base'))

            page = request.GET.get('page', 1)
            paginator = Paginator(filtro_list, 30)

            try:
                productos = paginator.page(page)
            except PageNotAnInteger:
                productos = paginator.page(1)
            except EmptyPage:
                productos = paginator.page(paginator.num_pages)

            datos = {
                'is_paginated':  True if paginator.num_pages > 1 else False,
                'page_obj': productos,
            }

            return render(request, "inventarios/List.html", datos)
        else:
            return redirect('codeBackEnd:dashboard')
    else:
        return redirect('login')

def GetProduct(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            filtroCodigo = request.POST['codigoProduto']

            if filtroCodigo != '':
                try:
                    producto = Productos.objects.filter(codigoProduto=filtroCodigo)
                except Productos.DoesNotExist:
                    return JsonResponse({"error": True, "existe": 0})

                if producto:
                    productoEncontrado = {
                        'nombre': producto[0].nombre,
                        'id': producto[0].id,
                    }
                    return JsonResponse(productoEncontrado)
                else:
                    return JsonResponse({"error": True, "existe": 0})
            else:
                return JsonResponse({"error": True})
        else:
            return JsonResponse({"error": True})
    else:
        return JsonResponse({ "error": True, "msj": "No authenticated" })

def AddProduct(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            datosInventario = {
                'descripcion':request.POST['descripcion'],
                'categoria':request.POST.getlist('categoria[]'),
                'codigoProduto':request.POST['codigoProduto'],
                'cantidad':request.POST['cantidad'],
                'nombre':request.POST['nombre'],
            }

            form = BaseForm(datosInventario)
            if form.is_valid():
                form.save()
                return JsonResponse({ "error": False, "msj": "Saved" })
            else:
                return JsonResponse({ "error": True, "msj": "Errors found" })
        else:
            return JsonResponse({ "error": True, "msj": "Method not allowed" })
    else:
        return JsonResponse({ "error": True, "msj": "No authenticated" })

def exportExcel(request):
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'transaccionesInventarios.view_transacciones'):
            filtroNombre = request.GET.get('nombre', '')
            filtroCodigo = request.GET.get('codigoProduto', '')
            filtroCategoria = request.GET.get('categoria', '')

            # trae los Transacciones relacionados
            filtro_list = []

            if filtroNombre != '' and filtroNombre != None:
                filtro_list = Productos.objects.filter(nombre__icontains=filtroNombre)
            elif filtroCodigo != '' and filtroCodigo != None:
                filtro_list = Productos.objects.filter(codigoProduto__icontains=filtroCodigo)
            elif filtroCategoria != '' and filtroCategoria != None:
                filtro_list = Productos.objects.filter(categoria__id=filtroCategoria)
            else:
                filtro_list = Productos.objects.all()

            datosExcel = []

            for producto in filtro_list:

                listaCategorias = ""
                for categoria in producto.categoria.all():
                    if listaCategorias == "":
                        listaCategorias = categoria.nombre
                    else:
                        listaCategorias = listaCategorias +", "+ categoria.nombre

                linea = [[
                    producto.id,
                    producto.nombre,
                    producto.cantidad,
                    producto.codigoProduto,
                    producto.descripcion,
                    listaCategorias,
                ]]
                datosExcel = datosExcel + linea

            titulos = [[
                "N. Inventario",
                "Nombre",
                "Cantidad",
                "Codigo del Produto",
                "Descripción",
                "Categoría",
            ],]

            excelExportar = estructuraExcel(titulos, datosExcel, 'transacciones')

            # return the response
            return excelExportar
        else:
            return redirect('codeBackEnd:dashboard')

    else:
        return redirect('login')

inventarios/inventarios/templates/inventarios/Add.html
{% extends 'codeBackEnd/base.html' %}
{% load static %}
{% load inventarios_extras %}
{% block title %}Nuevo producto{% endblock %}
{% block tituloSeccion %}<img class="img-titulo" src="{% static 'codeBackEnd/admin/img/png/box.png' %}"> Nuevo producto{% endblock %}

{% block customHead %}
    <link href="{% static 'codeBackEnd/admin/assets/dataTables/css/dataTables.bootstrap4.css' %}" rel="stylesheet"  type="text/css"/>
{% endblock %}

{% block customCss %}
    <style></style>
{% endblock %}

{% block content %}
    <form action="" id="formAdd" method="post" enctype="multipart/form-data" class="row ">
        {% csrf_token %}

        <div class="form-group col-md-6"> {% comment %} nombre {% endcomment %}
            {{ form.nombre.label_tag }}
            {{ form.nombre }}
            {{ form.nombre.errors }}
        </div>

        <div class="form-group col-md-6"> {% comment %} cantidad {% endcomment %}
            <label for="id_cantidad">Cantidad de existencias:</label>
            {{ form.cantidad }}
            {{ form.cantidad.errors }}
        </div>

        <div class="form-group col-md-6"> {% comment %} codigoProduto {% endcomment %}
            {{ form.codigoProduto.label_tag }}
            {{ form.codigoProduto }}
            {{ form.codigoProduto.errors }}
        </div>

        <div class="form-group col-md-6"> {% comment %} categoria {% endcomment %}
            {{ form.categoria.label_tag }}
            <div class="selectgroup w-100">
                <select id="id_categoria" name="categoria" class="selectpicker w-100" multiple data-live-search="true">
                    {% get_Categorias_list as categorias %}
                    {% for categoria in categorias %}
                        <option value="{{ categoria.id }}">{{ categoria.nombre }}</option> 
                    {% endfor%}
                </select>
            </div>
            {{ form.categoria.errors }}
        </div>

        <div class="form-group col-md-12"> {% comment %} descripcion {% endcomment %}
            {{ form.descripcion.label_tag }}
            {{ form.descripcion }}
            {{ form.descripcion.errors }}
        </div>

        <div class="form-group col-md-12 pr-0">
            <div class="row col-md-12 pr-0">
                <div class="text-center col-12 order-2 text-sm-left order-sm-1 col-sm-6 p-sm-0">
                    <a href="{% url 'Inventarios:Base' %}" type="button" class="btn btn-light"><i class="fas fa-chevron-left"></i> Volver al listado</a>
                </div>
                <div class="text-center col-12 mb-2 order-1 text-sm-right order-sm-2 mb-sm-0 col-sm-6 p-sm-0">
                    <button type="submit" class="btn btn-light">
                        <i class="far fa-save"></i> Guardar producto
                    </button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

{% block customJs %}
    <script src="{% static 'inventarios/assets/js/validar.js' %}"></script>
{% endblock %}

inventarios/inventarios/templates/inventarios/Del.html
{% extends 'codeBackEnd/base.html' %}
{% load humanize %}
{% load static %}
{% block title %}Borrar producto{% endblock %}
{% block tituloSeccion %}<img class="img-titulo" src="{% static 'codeBackEnd/admin/img/png/box.png' %}"> Borrar producto{% endblock %}

{% block customHead %}
    <link href="{% static 'codeBackEnd/admin/assets/dataTables/css/dataTables.bootstrap4.css' %}" rel="stylesheet"  type="text/css"/>
{% endblock %}

{% block customCss %}
    <style>
        tbody tr td{ color: #ffffff; }
        tbody tr td a{ color: #5C9FF1; padding-left: 10px; }
        .estado .alert{
            background-color: rgba(255,255,255,.05);
            margin-top: 10px;
            padding: .8rem 1rem;
        }
    </style>
{% endblock %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        <h2 class="text-white">¿Estás seguro de que quieres borrar "<b>{{ object }}</b>"?</h2>
        <input type="submit"  class="btn btn-danger float-right" value="Sí, borrar" />
    </form>
{% endblock %}

inventarios/inventarios/templates/inventarios/Edit.html
{% extends 'codeBackEnd/base.html' %}
{% load static %}
{% load inventarios_extras %}
{% block title %}Editar producto{% endblock %}
{% block tituloSeccion %}<img class="img-titulo" src="{% static 'codeBackEnd/admin/img/png/box.png' %}"> Editar producto{% endblock %}

{% block customCss %}
    <style>
    </style>
{% endblock %}

{% block content %}
    <form action="" id="formEdit" method="post" enctype="multipart/form-data" class="row ">
        {% csrf_token %}

        <div class="form-group col-md-12"> {% comment %} nombre {% endcomment %}
            {{ form.nombre.label_tag }}
            {{ form.nombre }}
            {{ form.nombre.errors }}
        </div>

        <div class="form-group col-md-6"> {% comment %} codigoProduto {% endcomment %}
            {{ form.codigoProduto.label_tag }}
            {{ form.codigoProduto }}
            {{ form.codigoProduto.errors }}
        </div>

        <div class="form-group col-md-6"> {% comment %} categoria {% endcomment %}
            {{ form.categoria.label_tag }}
            <div class="selectgroup w-100">
                <select id="id_categoria" name="categoria" class="selectpicker w-100" multiple data-live-search="true">
                    {% get_Categorias_list as categorias %}
                    {% for categoria in categorias %}
                        <option value="{{ categoria.id }}">{{ categoria.nombre }}</option> 
                    {% endfor%}
                </select>
            </div>
            {{ form.categoria.errors }}
        </div>

        <div class="form-group col-md-12"> {% comment %} descripcion {% endcomment %}
            {{ form.descripcion.label_tag }}
            {{ form.descripcion }}
            {{ form.descripcion.errors }}
        </div>

        <div class="form-group col-md-12 pr-0">
            <div class="row col-md-12 pr-0">
                <div class="text-center col-12 order-2 text-sm-left order-sm-1 col-sm-6 p-sm-0">
                    <a href="{% url 'Inventarios:Base' %}" type="button" class="btn btn-light"><i class="fas fa-chevron-left"></i> Volver al listado</a>
                </div>
                <div class="text-center col-12 mb-2 order-1 text-sm-right order-sm-2 mb-sm-0 col-sm-6 p-sm-0">
                    <button type="submit" class="btn btn-light">
                        <i class="far fa-save"></i> Guardar cambios
                    </button>
                </div>
            </div>
        </div>
    </form>

{% endblock %}

{% block customJs %}
    <script src="{% static 'inventarios/assets/js/validar.js' %}"></script>
    <script>
        {% if 'updated' in request.GET %}
            swal({
                title: "Realizado",
                text: "Se ha actualizado el producto",
                icon: "success",
                buttons: {
                    confirm: {
                        text: "OK",
                        value: true,
                        visible: true,
                        className: "btn btn-success",
                        closeModal: true
                    }
                }
            });
        {% endif %}

        function seleccionarAutomatico(){
            ListadoSeleccionados = [{% for categoria in object.categoria.all %}
                {{categoria.id}},
            {% endfor %}]

            $('#id_categoria').selectpicker('destroy');
            $("#id_categoria").val(ListadoSeleccionados);
            $('#id_categoria').selectpicker();
        }
        seleccionarAutomatico()
    </script>
{% endblock %}